export const defaultValueSorting = 'popular down';
export const defaultValueYears = 2020;
export const defaultValueGenres = 0;

export const defaultValueCollections = 'default collections';

export const ACTIONS_TYPE = {
  FILTERS_FETCHED: 'FILTERS_FETCHED',
  COLLECTIONS_FETCHED: 'COLLECTIONS_FETCHED',
  YEARS_FETCHED: 'YEARS_FETCHED',
  SORTING_FETCHED: 'SORTING_FETCHED',
  MOVIES_FETCHED: 'MOVIES_FETCHED',
  UPDATE_SORTING: 'UPDATE_SORTING',
  UPDATE_YEARS: 'UPDATE_YEARS',
  UPDATE_SELECTED_GENRES: 'UPDATE_SELECTED_GENRES',
  UPDATE_SELECTED_COLLECTIONS: 'UPDATE_SELECTED_COLLECTIONS',
  UPDATE_AUTHORIZATION: 'UPDATE_AUTHORIZATION',
};
