export const DEFAULT_VALUE = {
  COLLECTIONS: 'default collections',
  GENRES: 0,
  YEARS: 2020,
  SORTING: 'popular down',
  SELECTED_PAGE: 1,
  COUNT_MOVIES_PAGE: 8,
  RATING: 'high rating',
  POPULARITY: 'high popularity',
};

export const ACTIONS_TYPE = {
  UPDATE_RATING: 'UPDATE_RATING',
  UPDATE_POPULARITY: 'UPDATE_POPULARITY',
  FILTERS_FETCHED: 'FILTERS_FETCHED',
  MOVIES_FETCHED: 'MOVIES_FETCHED',
  UPDATE_SORTING: 'UPDATE_SORTING',
  UPDATE_YEARS: 'UPDATE_YEARS',
  UPDATE_SELECTED_GENRES: 'UPDATE_SELECTED_GENRES',
  UPDATE_SELECTED_COLLECTIONS: 'UPDATE_SELECTED_COLLECTIONS',
  UPDATE_AUTHORIZATION: 'UPDATE_AUTHORIZATION',
  UPDATE_SELECTED_PAGE: 'UPDATE_SELECTED_PAGE',
  RESET_SELECTED_PAGE: 'RESET_SELECTED_PAGE',
  FAVORITE_MOVIES_FETCHED: 'FAVORITE_MOVIES_FETCHED',
  WATCH_LATER_FETCHED: 'WATCH_LATER_FETCHED',
};
