export const DEFAULT_VALUE = {
  COLLECTIONS: 'default collections',
  GENRES: 0,
  YEARS: 2020,
  SORTING: 'popular down',
  SELECTED_PAGE: 1,
  COUNT_MOVIES_PAGE: 8,
};

export const ACTIONS_TYPE = {
  FILTERS_FETCHED: 'FILTERS_FETCHED',
  COLLECTIONS_FETCHED: 'COLLECTIONS_FETCHED',
  YEARS_FETCHED: 'YEARS_FETCHED',
  SORTING_FETCHED: 'SORTING_FETCHED',
  MOVIES_FETCHED: 'MOVIES_FETCHED',
  UPDATE_SORTING: 'UPDATE_SORTING',
  UPDATE_YEARS: 'UPDATE_YEARS',
  UPDATE_SELECTED_GENRES: 'UPDATE_SELECTED_GENRES',
  UPDATE_SELECTED_COLLECTIONS: 'UPDATE_SELECTED_COLLECTIONS',
  UPDATE_AUTHORIZATION: 'UPDATE_AUTHORIZATION',
  UPDATE_SELECTED_PAGE: 'UPDATE_SELECTED_PAGE',
  RESET_SELECTED_PAGE: 'RESET_SELECTED_PAGE',
};
